[package]
name = "ct-logs"
version = "0.9.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
readme = "README.md"
license = "Apache-2.0/ISC/MIT"
description = "Google's list of Certificate Transparency logs for use with sct crate"
homepage = "https://github.com/ctz/ct-logs"
repository = "https://github.com/ctz/ct-logs"

[dependencies]
sct = { git = "https://github.com/jyao1/sct.rs.git", branch = "uefi_support" }
